package com.grppj.donateblood.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.springframework.web.multipart.MultipartFile;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class User {
    private int id;
    private String username;
    private String email;
    private String password;
    private String confirmPassword;
    private String gender;
    private LocalDate dateofbirth;
    private String address;
    private String phone;  
    private RoleBean role;
    
    private Integer bloodTypeId;  // blood_type_id references blood_type table
    private Integer hospitalId;
    private String hospitalName;
    private MultipartFile filePart;
    private byte[] imageBytes;

    private String autoGeneratedCode;
    
    private LocalDateTime codeExpiry;
    
    private boolean isVerified = false;
    
    // ... getters and setters ...
    public boolean isCodeValid() {
        return codeExpiry != null && LocalDateTime.now().isBefore(codeExpiry);
    }

    

}
